### ISSUE TITLE
Invalid Parameter Error

### ISSUE THREAD

**Issue by Unorthodoxis-ui** [elosha/degooglepdf#3]
![image](https://github.com/elosha/degooglepdf/assets/64767966/0c8691fb-566a-48c8-b25a-289ecb4ded60)
I get this error when I try to use mkpdf.sh 

Not sure how to fix it.

**Comment by elosha** [comment]
Hi, thanks for reporting. I see the problem, I'm gonna fix this later today!

Workaround: Rename the .imgpack file so it doesn't contain spaces.

**Comment by Unorthodoxis-ui** [comment]
Wow you replied fast, I'll apply the workaround and let you know. Thanks!

**Comment by Unorthodoxis-ui** [comment]
Did the workaround and this happened:
[image: image.png]
[image: image.png]

Any idea where the output file went? The created folder is empty. Thanks.
[image: image.png]

**Comment by elosha** [comment]
Your screenshots didn't make it through the email gateway, please post them via web.

Can you please give information which browser and OS you use? Thanks 🙂 

The .pdf would end up in the same directory as the .imgpack .
Also strange if the images directory remains empty … this seems to be two issues in one.

**Comment by Unorthodoxis-ui** [comment]
Ill try to send them as attachments via Gmail.

**Comment by Unorthodoxis-ui** [comment]
![1](https://github.com/elosha/degooglepdf/assets/64767966/1c858a41-3049-4f55-b181-24307825629a)
![2](https://github.com/elosha/degooglepdf/assets/64767966/a17cdc16-3ade-44dc-938c-452ab471ac4d)
![3](https://github.com/elosha/degooglepdf/assets/64767966/2858e370-14ab-4bb1-877a-a4bcf4392d2d)

**Comment by Unorthodoxis-ui** [comment]
Here are the screenshots

**Comment by elosha** [comment]
It worked.

It seems the JS part didn't save any pages as images. What is the file size of board.imgpack?

Would you tell me the url of that PDF you're trying to save? So I can try in parallel …

**Comment by Unorthodoxis-ui** [comment]
https://drive.google.com/file/d/1eVVq1Mpo1vAppcU9C9_AQx-m1nENb5hC/view

this is the link to the pdf file.The board.imgpack size is 64,554kbs
 Board.imgpack
<https://drive.google.com/file/d/1GtJliqE7qRYl-MTcaTAFsCjEnoPv7pk2/view?usp=drive_web>


Oh I forgot to answer, my browser is Opera Gx, and my OS is Windows 10.

**Comment by Unorthodoxis-ui** [comment]
https://drive.google.com/file/d/1eVVq1Mpo1vAppcU9C9_AQx-m1nENb5hC/view

this is the link to the pdf file.The board.imgpack size is 64,554kbs

**Comment by elosha** [comment]
I was able to download & produce a PDF. The file size of .imgpack was the same like yours, while the PDF was 48.6MB 👍 

I'm working on more reliable parameter parsing, please try the current version (5aa3a5b6e60f15474ea2159eb64217387d83aea3).

> The folder is empty.

The script only checks if the folder exists, not if it contains files. Say 'n' when it asks you if you want to use these files (which don't exist) so extraction will be tried again.

I need to know why the script didn't put any files in this folder.

**Comment by Unorthodoxis-ui** [comment]
I tried the new version now, seems like it still doesn't produce a pdf on my end, it just creates an empty folder.

**Comment by elosha** [comment]
@Unorthodoxis-ui
Let's try to find out the reason. I don't have Windows so this is interesting for me ;)

Do you have **sed** installed?
Try running `which sed` in command line – it should either display "sed not found" or a path where sed is located.

**Comment by Unorthodoxis-ui** [comment]
Oh wait, Turns out I did something wrong, its extracting now

**Comment by Unorthodoxis-ui** [comment]
Alright, it worked! Thank you so much man, appreciate the help.

**Comment by elosha** [comment]
@Unorthodoxis-ui Glad it worked :)
